### ISSUE TITLE
코드 공개

### ISSUE THREAD

**Issue by gyunggyung** [juheo/Adversarially-Trained-End-to-end-Korean-Singing-Voice-Synthesis-System#1]
안녕하세요.

혹시 코드와 데이터셋은 공개하실 생각이 없으신지 문의드립니다.

제가 직접 테스트 했을때도 이렇게 좋은 퀄리티의 음악이 나오는지 궁금합니다!

감사합니다.

**Comment by juheo** [comment]
안녕하세요. 우선 저희 연구에 관심을 가져주셔서 감사합니다.

안타깝게도 학습데이터의 경우 내부 연구목적으로 사용하는것에 대한 동의만을 받은 후 직접 수집하였기 때문에 공개는  근 시일 내에는 어려울 것으로 판단됩니다.

학습 코드의 경우 정부과제의 한 부분로 진행되었던 연구이기 때문에 전체 공유가 가능한지에 대해 확인해보아야 할 부분이 있고, 현재 다른 업무로 이에 대한 진행은 보류되고 있는 상황입니다. 다만 논문 내용을 토대로 구현하시는 도중 궁금하신 내용에 대해 답변드리는것은 가능할 것 같습니다.

관심가져주심에 감사드리고, 추후 업데이트가 생긴다면 공지드리겠습니다.

==============================================

Q. Are you planning to release your training data and code?
A. Unfortunately, since the training data was collected directly after receiving consent for use for internal research purposes, it would be difficult to disclose it in the near future. In the case of the training code, it is a study that was conducted as a part of the government project, so there is a part to check whether it is possible to share the entire work. However, it may be possible to answer any questions you may have during the implementation based on the [paper ](https://arxiv.org/abs/1908.01919)content.

**Comment by gyunggyung** [comment]
답변 감사합니다 :)

2020년 5월 15일 (금) 오후 7:02, Juheon <notifications@github.com>님이 작성:
