### ISSUE TITLE
How to deal with polyphonic phoneme in a song?

### ISSUE THREAD

**Issue by xw1324832579** [juheo/Adversarially-Trained-End-to-end-Korean-Singing-Voice-Synthesis-System#2]
Hello, @juheo  I have a question about input representation, in general, "in Korean, we assigned onset and coda to the first and the last frame of input text array, respectively, and the rest of the frames with nucleus."  
    However, in many songs during data collection, polyphonic words are common.
In this case, how should frames be distributed to onset, coda and nucleus?

**Comment by juheo** [comment]
Hi @xw1324832579  ! Thank you for your interest in my research. 

When we collected our singing voice dataset, we recorded a waveform sung by one singer. So we could assume that each frame corresponds to only one pronunciation (=phoneme)

I don't understand exactly the 'polyphonic words' you asked. Are you referring to the case where two or more voices sing with different lyrics at a time? If so, I can say that our model was not trained to model such data, but was trained on a single vocal track.

**Comment by juheo** [comment]
If you're asking about a language other than Korean, a syllable consisting of more than 3 phonemes, we can answer that we are also contemplating the problem.

The best way to do this is to get phoneme-level alignment, but this is expensive. Therefore, as assumed in Korean, after analyzing the phoneme included in one word, we can apply a method of giving a relatively long duration for the phoneme corresponding to the vowel and short duration for the remaining phoneme.

we applied this study to the NUS-48E dataset, and in this case, the phoneme alignment was present, so we could experiment on the same framework without any problems.

**Comment by xw1324832579** [comment]
> Hi @xw1324832579 ! Thank you for your interest in my research.
> 
> When we collected our singing voice dataset, we recorded a waveform sung by one singer. So we could assume that each frame corresponds to only one pronunciation (=phoneme)
> 
> I don't understand exactly the 'polyphonic words' you asked. Are you referring to the case where two or more voices sing with different lyrics at a time? If so, I can say that our model was not trained to model such data, but was trained on a single vocal track.
Thank you for your reply, I'm sorry I didn't make myself clear.What I mean is that one word maybe corresponding to more than one pitch(note) in a sentence. For example，the lyrics is"love",and its correspond pitch input is 78[1,5] 79[5,8].In this case, how should frames be distributed to onset, coda and nucleus? Or  there is no such data your training dataset?

**Comment by juheo** [comment]
If we write the English word 'love' in Korean, it is [러브]. In Korean, it is expressed as two syllables, and each two syllables can be separated by phoneme of [ㄹ, ㅓ,' '], [ㅂ, ㅡ,' ']. In this case, there are no codas. 

Since we assumed in our study that one syllable, not one word, corresponds to one note, in the above situation, we can determine the phoneme distribution for each syllable. (If there is no coda in syllable, the last frame is also allocated as nuclues.)

If it is English, it can be separated by love = [L, AH, V] based on the CMU dictionary. However, if the part corresponding to V is sung as an independent note, we can separate it into expressions such as [L, AH] + [V A], or [L, AH] + [V Z].

In general, even in the case of an English song, we figured out that each note contains one vowel, and after separating the notes based on this vowel, we think that a similar approach can be used, but more detailed rules are still studied.
